version: '3.4'

services:
   
  # Our own services

  Jenner.Monolith:
    environment:
      - ConnectionStrings__MongoDb=mongodb+srv://jennermonolith:250793@jennermonolith.l8egivl.mongodb.net/?retryWrites=true&w=majority      
      - ASPNETCORE_URLS=http://+:80
      - Logging__LogLevel__Default=Error
    ports:
      - "6020:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
