version: '3.4'

services:
   
  mongo.db.monolith:
    container_name: mongo-db-monolith
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: imroot

  mongo.explorer.monolith:
    container_name: mongo-gui-monolith
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:imroot@mongo.db:27017/
    depends_on:
      - mongo.db.monolith

  # Our own services

  Jenner.Monolith:
    environment:
      - ConnectionStrings__MongoDb=mongodb://root:imroot@mongo.db.monolith:27017/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6020:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - mongo.db.monolith