version: '3.4'

services:
   
  #mongo.db.monolith:
  #  container_name: mongo-db-monolith
  #  image: mongo
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: imroot

  mongo.explorer.monolith:
    container_name: mongo-gui-monolith
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb+srv://jennermonolith:D2RDqXHhqTnuwbot@jennermonolith.jpj80ow.mongodb.net/?retryWrites=true&w=majority

  # Our own services

  Jenner.Monolith:
    environment:
      - ConnectionStrings__MongoDb=mongodb+srv://jennermonolith:D2RDqXHhqTnuwbot@jennermonolith.jpj80ow.mongodb.net/?retryWrites=true&w=majority
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6020:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
