name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: "Extract Branch name"
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: "Login to GitHub registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CM_TOKEN }}    
    
    - name: "Publish the image Jenner.Monolith.Api"
      uses: docker/build-push-action@v2
      with:
        file: ./Jenner.Monolith/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/callebmc/jenner/jennermonolith:${{ github.sha }}
          ghcr.io/callebmc/jenner/jennermonolith:${{ env.BRANCH }}
